### ISSUE TITLE
Cambios esteticos en la página de login

### ISSUE THREAD

**Issue by emiarias** [Agustin-Indarte/Blog-Web-Tech#9]
Proceso
La imagen 'ingresa al universo IT' de la página login, en dispositivos medianos se ve hacia la izquierda y queda un espacio a la derecha vacio, el formulario que viene abajo esta centrado. La recomendación es distribuir el espacio sobrante de la imagen en partes iguales a la izquierda y derecha para lograr mas armonia. En dispositivos pequeños y grandes se ve muy bien

Captura
![image](https://github.com/user-attachments/assets/d64597a3-085c-4ec4-9cba-f763ba4157ec)

**Comment by MaritoSebastian** [comment]
Se realiza la corrección centrando el primer contenedor
captura

![image](https://github.com/user-attachments/assets/0b333709-0ce6-43d6-88e6-992be378272d)

**Comment by emiarias** [comment]
Esta issue no fue corregida, verifiquen si subieron los cambios que realizaron a producción, ya que se sigue viendo igual que antes

![image](https://github.com/user-attachments/assets/eb9b0312-f7fa-446f-828d-631bd0356bd2)
